/*     
 *    
 *  Author     : Neal DeBuhr
 *  Version    : DEVS-Suite 3.0.0  
 *  Date       : 12-27-2017
 */
package CoreOne;
import java.awt.*;

import GenCol.*;

import model.modeling.*;
import model.simulation.*;

import view.modeling.ViewableAtomic;
import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;
import view.simView.*;

public class Empty extends ViewableDigraph {
    // Workaround for creating "joints" in the SimView coupling traces
    private ViewableAtomic unit;
    private String nameForUnits;
    public int blackBoxWidthSpec;
    public int blackBoxHeightSpec;

    public Empty(){
	this("Empty", "Object");
    }
    
    public Empty(String name, String name_for_units){
	super(name);
	nameForUnits = name_for_units;
	blackBox = true;
	blackBoxWidthSpec = 21;
	blackBoxHeightSpec = 81;
	
	unit = new EmptyUnit("EmptyUnit", nameForUnits);

	add(unit);
	
	addInports();
	addOutports();
	addCouplings();
    }

    private void addInports(){
	addInport("0-in");
	addInport("1-in");
	addInport("2-in");
	addInport("3-in");
	addInport("4-in");
	addInport("5-in");
    }
    
    private void addOutports(){
	addOutport("0-out");
	addOutport("1-out");
	addOutport("2-out");
	addOutport("3-out");
	addOutport("4-out");
	addOutport("5-out");
    }
   
    private void addCouplings(){
	addCoupling(this, "0-in", unit, "0-in");
	addCoupling(this, "1-in", unit, "1-in");
	addCoupling(this, "2-in", unit, "2-in");
	addCoupling(this, "3-in", unit, "3-in");
	addCoupling(this, "4-in", unit, "4-in");
	addCoupling(this, "5-in", unit, "5-in");
	addCoupling(unit, "0-out", this, "0-out");
	addCoupling(unit, "1-out", this, "1-out");
	addCoupling(unit, "2-out", this, "2-out");
	addCoupling(unit, "3-out", this, "3-out");
	addCoupling(unit, "4-out", this, "4-out");
	addCoupling(unit, "5-out", this, "5-out");
    }

    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(21, 81);
        ((ViewableComponent)withName("EmptyUnit1")).setPreferredLocation(new Point(22, 126));
        ((ViewableComponent)withName("EmptyUnit4")).setPreferredLocation(new Point(28, 211));
        ((ViewableComponent)withName("EmptyUnit0")).setPreferredLocation(new Point(21, 269));
        ((ViewableComponent)withName("EmptyUnit2")).setPreferredLocation(new Point(15, 314));
        ((ViewableComponent)withName("EmptyUnit3")).setPreferredLocation(new Point(-5, 212));
        ((ViewableComponent)withName("EmptyUnit5")).setPreferredLocation(new Point(50, 50));
    }
}
