/*     
 *    
 *  Author     : Neal DeBuhr
 *  Version    : DEVS-Suite 3.0.0  
 *  Date       : 12-27-2017
 */
package CoreOne;
import java.awt.*;

import GenCol.*;

import model.modeling.*;
import model.simulation.*;

import view.modeling.ViewableAtomic;
import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;
import view.simView.*;

public class GitHub extends ViewableDigraph {
    private ViewableAtomic inst0;
    private ViewableAtomic inst1;
    private ViewableAtomic inst2;
    private ViewableAtomic inst3;
    private ViewableAtomic inst4;
    private ViewableAtomic inst5;
    
    public GitHub(){
	super("GitHub");
	blackBox = true;
	inst0 = new GithubRepo("GitHub Instance 0",
			       "cuahsi-qa-automation-engine");
	inst1 = new GithubRepo("GitHub Instance 1",
			       "cuahsi-qa-automation-engine");
	inst2 = new GithubRepo("GitHub Instance 2",
			       "cuahsi-qa-automation-engine");
	inst3 = new GithubRepo("GitHub Instance 3",
			       "cuahsi-qa-automation-engine");
	inst4 = new GithubRepo("GitHub Instance 4",
			       "cuahsi-qa-automation-engine");
	inst5 = new GithubRepo("GitHub Instance 5",
			       "cuahsi-qa-automation-engine");

	add(inst0);
	add(inst1);
	add(inst2);
	add(inst3);
	add(inst4);
	add(inst5);

	addInports();
	addOutports();
	addCouplings();
    }

    private void addInports(){
	addInport("0-in");
	addInport("1-in");
	addInport("2-in");
	addInport("3-in");
	addInport("4-in");
	addInport("5-in");
    }
    
    private void addOutports(){
	addOutport("0-out");
	addOutport("1-out");
	addOutport("2-out");
	addOutport("3-out");
	addOutport("4-out");
	addOutport("5-out");
    }
   
    private void addCouplings(){
	addCoupling(this, "0-in", inst0, "in");
	addCoupling(this, "1-in", inst1, "in");
	addCoupling(this, "2-in", inst2, "in");
	addCoupling(this, "3-in", inst3, "in");
	addCoupling(this, "4-in", inst4, "in");
	addCoupling(this, "5-in", inst5, "in");
	addCoupling(inst0, "out", this, "0-out");
	addCoupling(inst1, "out", this, "1-out");
	addCoupling(inst2, "out", this, "2-out");
	addCoupling(inst3, "out", this, "3-out");
	addCoupling(inst4, "out", this, "4-out");
	addCoupling(inst5, "out", this, "5-out");
    }

    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(591, 381);
        ((ViewableComponent)withName("GitHub Instance 1")).setPreferredLocation(new Point(150, 84));
        ((ViewableComponent)withName("GitHub Instance 4")).setPreferredLocation(new Point(154, 267));
        ((ViewableComponent)withName("GitHub Instance 5")).setPreferredLocation(new Point(152, 323));
        ((ViewableComponent)withName("GitHub Instance 2")).setPreferredLocation(new Point(150, 146));
        ((ViewableComponent)withName("GitHub Instance 3")).setPreferredLocation(new Point(152, 205));
        ((ViewableComponent)withName("GitHub Instance 0")).setPreferredLocation(new Point(147, 27));
    }
}
