/*     
 *    
 *  Author     : Neal DeBuhr
 *  Version    : DEVS-Suite 3.0.0  
 *  Date       : 12-27-2017
 */
package CoreOne;
import java.awt.*;

import GenCol.*;

import model.modeling.*;
import model.simulation.*;

import view.modeling.ViewableAtomic;
import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;
import view.simView.*;

public class JenkinsOnline extends ViewableDigraph {
    private ViewableDigraph jenkins;
    private ViewableAtomic email;
    
    public JenkinsOnline(){
	super("JenkinsOnline");
	jenkins = new Jenkins();
	email = new NealEmail();

	add(jenkins);
	add(email);

	addInports();
	addOutports();
	addCouplings();
    }

    private void addInports(){
	addInport("grid-0-in");
	addInport("grid-1-in");
	addInport("grid-2-in");
	addInport("grid-3-in");
	addInport("grid-4-in");

	addInport("github-0-in");
	addInport("github-1-in");
	addInport("github-2-in");
	addInport("github-3-in");
	addInport("github-4-in");
	addInport("github-5-in");
    }
    
    private void addOutports(){
	addOutport("grid-0-out");
	addOutport("grid-1-out");
	addOutport("grid-2-out");
	addOutport("grid-3-out");
	addOutport("grid-4-out");

	addOutport("github-0-out");
	addOutport("github-1-out");
	addOutport("github-2-out");
	addOutport("github-3-out");
	addOutport("github-4-out");
	addOutport("github-5-out");
    }
   
    private void addCouplings(){
	addCoupling(jenkins, "coord-github-request", this, "github-0-out");
	addCoupling(jenkins, "job0-github-request", this, "github-1-out");
	addCoupling(jenkins, "job1-github-request", this, "github-2-out");
	addCoupling(jenkins, "job2-github-request", this, "github-3-out");
	addCoupling(jenkins, "job3-github-request", this, "github-4-out");
	addCoupling(jenkins, "job4-github-request", this, "github-5-out");

	addCoupling(this, "github-0-in", jenkins, "coord-github-response");
	addCoupling(this, "github-1-in", jenkins, "job0-github-response");
	addCoupling(this, "github-2-in", jenkins, "job1-github-response");
	addCoupling(this, "github-3-in", jenkins, "job2-github-response");
	addCoupling(this, "github-4-in", jenkins, "job3-github-response");
	addCoupling(this, "github-5-in", jenkins, "job4-github-response");

	addCoupling(jenkins, "results", email, "in");

	addCoupling(this, "grid-0-in", jenkins, "job0-grid-in");
	addCoupling(this, "grid-1-in", jenkins, "job1-grid-in");
	addCoupling(this, "grid-2-in", jenkins, "job2-grid-in");
	addCoupling(this, "grid-3-in", jenkins, "job3-grid-in");
	addCoupling(this, "grid-4-in", jenkins, "job4-grid-in");

	addCoupling(jenkins, "job0-grid-out", this, "grid-0-out");
	addCoupling(jenkins, "job1-grid-out", this, "grid-1-out");
	addCoupling(jenkins, "job2-grid-out", this, "grid-2-out");
	addCoupling(jenkins, "job3-grid-out", this, "grid-3-out");
	addCoupling(jenkins, "job4-grid-out", this, "grid-4-out");
    }

    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(1290, 749);
        ((ViewableComponent)withName("JenkinsJobs")).setPreferredLocation(new Point(196, 212));
        ((ViewableComponent)withName("NealEmail")).setPreferredLocation(new Point(673, 659));
    }
}
