/*     
 *    
 *  Author     : Neal DeBuhr
 *  Version    : DEVS-Suite 3.0.0  
 *  Date       : 12-27-2017
 */
package CoreOne;
import java.awt.*;

import GenCol.*;

import model.modeling.*;
import model.simulation.*;

import view.modeling.ViewableAtomic;
import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;
import view.simView.*;

public class Jenkins extends ViewableDigraph {
    protected int number_nodes;
    protected int number_jobs;
    
    public Jenkins(){
	super("Jenkins");
	number_nodes = 3;
	number_jobs = 10;
	
	ViewableAtomic hub = new SeleniumGridHub("SeleniumGridHub", number_nodes, number_jobs);
	ViewableAtomic coord = new JenkinsCoord();
	ViewableAtomic email = new NealEmail();
	
	add(hub);
	add(coord);
	add(email);

	addInport("trigger");
	addInport("executor0-in");
	addInport("executor1-in");
	addInport("executor2-in");
	addInport("github-in");
	
	addOutport("executor0-out");
	addOutport("executor1-out");
	addOutport("executor2-out");
	addOutport("github-out");
	addOutport("results");

	addCoupling(this, "trigger", coord, "setup-in");
	addCoupling(coord, "setup-out", this, "github-out");
	addCoupling(this, "github-in", hub, "code");
	addCoupling(hub, "suite-status", coord, "results-in");
	addCoupling(coord, "results-out", this, "results");
	addCoupling(coord, "results-out", email, "in");
	
	addCoupling(this, "executor0-in", hub, "status0");
	addCoupling(this, "executor1-in", hub, "status1");
	addCoupling(this, "executor2-in", hub, "status2");
	addCoupling(hub, "out0", this, "executor0-out");
	addCoupling(hub, "out1", this, "executor1-out");
	addCoupling(hub, "out2", this, "executor2-out");

	addTestInput("trigger", new entity("GitHub Pull Request"), 0);
	addTestInput("trigger", new entity("Beta System Deployment"), 0);
	addTestInput("trigger", new entity("Scheduled Suite Execution"), 0);
    }
    
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(710, 477);
        ((ViewableComponent)withName("JenkinsCoord")).setPreferredLocation(new Point(109, 392));
        ((ViewableComponent)withName("NealEmail")).setPreferredLocation(new Point(287, 335));
        ((ViewableComponent)withName("SeleniumGridHub")).setPreferredLocation(new Point(120, 247));
    }
}
