/*     
 *    
 *  Author     : Neal DeBuhr
 *  Version    : DEVS-Suite 3.0.0  
 *  Date       : 12-27-2017
 */
package CoreOne;
import java.awt.*;

import GenCol.*;

import model.modeling.*;
import model.simulation.*;

import view.modeling.ViewableAtomic;
import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;
import view.simView.*;

public class TestingEngine extends ViewableDigraph {
    protected int number_nodes;
    protected int number_jobs;
    // protected Array executors;
    
    public TestingEngine(){
	super("TestingEngine");
	number_nodes = 3;
	number_jobs = 10;
	
	ViewableDigraph jenkins = new Jenkins();
	ViewableAtomic github = new GithubRepo();
	// Fix below later for extensibility
	ViewableAtomic node0 = new SeleniumGridNode("SeleniumGridNode0", 1);
	ViewableAtomic node1 = new SeleniumGridNode("SeleniumGridNode1", 1);
	ViewableAtomic node2 = new SeleniumGridNode("SeleniumGridNode2", 1);
	ViewableAtomic site = new SimpleDjangoSite();
	
	add(jenkins);
	add(github);
	add(node0);
	add(node1);
	add(node2);
	add(site);
	
	addCoupling(github, "out", jenkins, "github-in");
	addCoupling(jenkins, "github-out", github, "in");

	addCoupling(node0, "out", jenkins, "executor0-in");
	addCoupling(node1, "out", jenkins, "executor1-in");
	addCoupling(node2, "out", jenkins, "executor2-in");
	addCoupling(jenkins, "executor0-out", node0, "in");
	addCoupling(jenkins, "executor1-out", node1, "in");
	addCoupling(jenkins, "executor2-out", node2, "in");

	addCoupling(jenkins, "results", site, "in");
    }
    
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(1124, 597);
        ((ViewableComponent)withName("SimpleDjangoSite")).setPreferredLocation(new Point(760, 493));
        ((ViewableComponent)withName("Jenkins")).setPreferredLocation(new Point(25, 20));
        ((ViewableComponent)withName("SeleniumGridNode1")).setPreferredLocation(new Point(793, 99));
        ((ViewableComponent)withName("SeleniumGridNode2")).setPreferredLocation(new Point(790, 216));
        ((ViewableComponent)withName("SeleniumGridNode0")).setPreferredLocation(new Point(789, 9));
        ((ViewableComponent)withName("GithubRepo")).setPreferredLocation(new Point(258, 545));
    }
}
