/*     
 *    
 *  Author     : Neal DeBuhr
 *  Version    : DEVS-Suite 3.0.0  
 *  Date       : 12-27-2017
 */
package CoreOne;
import java.awt.*;

import GenCol.*;

import model.modeling.*;
import model.simulation.*;

import view.modeling.ViewableAtomic;
import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;
import view.simView.*;

public class TestingEngine extends ViewableDigraph {
    protected int number_nodes;
    protected int number_jobs;
    // protected Array executors;
    
    public TestingEngine(){
	super("TestingEngine");
	number_nodes = 3;
	number_jobs = 10;
	
	ViewableDigraph jenkins = new Jenkins();
	ViewableAtomic github = new GithubRepo();
	// Fix below later for extensibility
	ViewableAtomic node0 = new SeleniumGridNode("SeleniumGridNode0", 1);
	ViewableAtomic node1 = new SeleniumGridNode("SeleniumGridNode1", 1);
	ViewableAtomic node2 = new SeleniumGridNode("SeleniumGridNode2", 1);
	
	add(jenkins);
	add(github);
	add(node0);
	add(node1);
	add(node2);
	
	addCoupling(github, "out", jenkins, "GithubIn");
	addCoupling(jenkins, "GithubOut", github, "in");

	addCoupling(node0, "out", jenkins, "executor0in");
	addCoupling(node1, "out", jenkins, "executor1in");
	addCoupling(node2, "out", jenkins, "executor2in");
	addCoupling(jenkins, "executor0out", node0, "in");
	addCoupling(jenkins, "executor1out", node1, "in");
	addCoupling(jenkins, "executor2out", node2, "in");
    }
    
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(591, 269);
	
    }
}
