/*     
 *    
 *  Author     : Neal DeBuhr
 *  Version    : DEVS-Suite 3.0.0  
 *  Date       : 12-27-2017
 */
package CoreOne;
import java.awt.*;

import GenCol.*;

import model.modeling.*;
import model.simulation.*;

import view.modeling.ViewableAtomic;
import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;
import view.simView.*;

public class GitHub extends ViewableDigraph {
    private ViewableAtomic inst0;
    private ViewableAtomic inst1;
    private ViewableAtomic inst2;
    private ViewableAtomic inst3;
    private ViewableAtomic inst4;
    
    public GitHub(){
	super("GitHub");
	inst0 = new GitHubRepo("GitHub Instance 0");
	inst1 = new GitHubRepo("GitHub Instance 1");
	inst2 = new GitHubRepo("GitHub Instance 2");
	inst3 = new GitHubRepo("GitHub Instance 3");
	inst4 = new GitHubRepo("GitHub Instance 4");

	add(inst0);
	add(inst1);
	add(inst2);
	add(inst3);
	add(inst4);

	addInports();
	addOutports();
	addCouplings();
    }

    private void addInports(){
	addInport("0");
	addInport("1");
	addInport("2");
	addInport("3");
	addInport("4");
    }
    
    private void addOutports(){
	addOutport("0");
	addOutport("1");
	addOutport("2");
	addOutport("3");
	addOutport("4");
    }
   
    private void addCouplings(){
	addCoupling(this, "0", inst0, "in");
	addCoupling(this, "1", inst1, "in");
	addCoupling(this, "2", inst2, "in");
	addCoupling(this, "3", inst3, "in");
	addCoupling(this, "4", inst4, "in");
	addCoupling(inst0, "out", this, "0");
	addCoupling(inst1, "out", this, "1");
	addCoupling(inst2, "out", this, "2");
	addCoupling(inst3, "out", this, "3");
	addCoupling(inst4, "out", this, "4");
    }

    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(591, 269);
	
    }
}
