/*     
 *    
 *  Author     : Neal DeBuhr
 *  Version    : DEVS-Suite 3.0.0  
 *  Date       : 12-27-2017
 */
package CoreOne;
import java.awt.*;

import GenCol.*;

import model.modeling.*;
import model.simulation.*;

import view.modeling.ViewableAtomic;
import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;
import view.simView.*;

public class Jenkins extends ViewableDigraph {
    protected int numberNodes;
    protected int numberJobs;
    private ViewableAtomic hub;
    private ViewableAtomic coord;
    private ViewableAtomic email;
    
    public Jenkins(){
	super("Jenkins");
	numberNodes = 3; //For later extensibility
	numberJobs = 10; //For later extensibility
	
	hub = new SeleniumGridHub("SeleniumGridHub", numberNodes, numberJobs);
	coord = new JenkinsCoord();
	email = new NealEmail();
	
	add(hub);
	add(coord);
	add(email);

	addInports();
	addOutports();
	addCouplings();
	addTestInputs();
    }

    private void addInports(){
	addInport("trigger");
	addInport("executor0-in");
	addInport("executor1-in");
	addInport("executor2-in");
	addInport("github-in");
    }
    
    private void addOutports(){
	addOutport("executor0-out");
	addOutport("executor1-out");
	addOutport("executor2-out");
	addOutport("github-out");
	addOutport("results");
    }
   
    private void addCouplings(){
	addCoupling(this, "trigger", coord, "setup-in");
	addCoupling(coord, "setup-out", this, "github-out");
	addCoupling(this, "github-in", hub, "code");
	addCoupling(hub, "suite-status", coord, "results-in");
	addCoupling(coord, "results-out", this, "results");
	addCoupling(coord, "results-out", email, "in");
	
	addCoupling(this, "executor0-in", hub, "status0");
	addCoupling(this, "executor1-in", hub, "status1");
	addCoupling(this, "executor2-in", hub, "status2");
	addCoupling(hub, "out0", this, "executor0-out");
	addCoupling(hub, "out1", this, "executor1-out");
	addCoupling(hub, "out2", this, "executor2-out");
    }

    private void addTestInputs(){
	addTestInput("trigger", new entity("GitHub Pull Request"), 0);
	addTestInput("trigger", new entity("Beta System Deployment"), 0);
	addTestInput("trigger", new entity("Scheduled Suite Execution"), 0);
    }
    
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(591, 269);
	
    }
}
