/*     
 *    
 *  Author     : Neal DeBuhr
 *  Version    : DEVS-Suite 3.0.0  
 *  Date       : 12-27-2017
 */
package CoreOne;
import java.awt.*;

import GenCol.*;

import model.modeling.*;
import model.simulation.*;

import view.modeling.ViewableAtomic;
import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;
import view.simView.*;

public class JenkinsOnline extends ViewableDigraph {
    private ViewableDigraph jenkins;
    private ViewableDigraph github;
    
    public JenkinsOnline(){
	super("JenkinsOnline");
	jenkins = new Jenkins("Jenkins");
	github = new GitHub("GitHub");

	add(jenkins);
	add(github);

	addInports();
	addOutports();
	addCouplings();
    }

    private void addInports(){
    }
    
    private void addOutports(){
    }
   
    private void addCouplings(){
	addCoupling(jenkins, "job0-github-request", github, "0");
	addCoupling(jenkins, "job1-github-request", github, "1");
	addCoupling(jenkins, "job2-github-request", github, "2");
	addCoupling(jenkins, "job3-github-request", github, "3");
	addCoupling(jenkins, "job4-github-request", github, "4");
	addCoupling(jenkins, "coord-github-request", github, "5");
	
	addCoupling(github, "0", jenkins, "job0-github-response");
	addCoupling(github, "1", jenkins, "job1-github-response");
	addCoupling(github, "2", jenkins, "job2-github-response");
	addCoupling(github, "3", jenkins, "job3-github-response");
	addCoupling(github, "4", jenkins, "job4-github-response");
	addCoupling(github, "5", jenkins, "coord-github-response");
    }

    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(591, 269);
	
    }
}
