/*     
 *    
 *  Author     : Neal DeBuhr
 *  Version    : DEVS-Suite 3.0.0  
 *  Date       : 12-27-2017
 */
package CoreOne;
import java.awt.*;

import GenCol.*;

import model.modeling.*;
import model.simulation.*;

import view.modeling.ViewableAtomic;
import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;
import view.simView.*;

public class Jenkins extends ViewableDigraph {
    protected int number_nodes;
    protected int number_jobs;
    
    public Jenkins(){
	super("Jenkins");
	number_nodes = 3;
	number_jobs = 10;
	
	ViewableAtomic hub = new SeleniumGridHub("SeleniumGridHub", number_nodes, number_jobs);
	ViewableAtomic coord = new JenkinsCoord();
	
	add(hub);
	add(coord);

	addInport("trigger");
	addInport("executor0in");
	addInport("executor1in");
	addInport("executor2in");
	addInport("GithubIn");
	
	addOutport("executor0out");
	addOutport("executor1out");
	addOutport("executor2out");
	addOutport("GithubOut");
	addOutport("results");

	addCoupling(this, "trigger", coord, "setup-in");
	addCoupling(coord, "setup-out", this, "GithubOut");
	addCoupling(this, "GithubIn", hub, "control");
	addCoupling(hub, "suite-status", coord, "results-in");
	addCoupling(coord, "results-out", this, "results");
	
	addCoupling(this, "executor0in", hub, "status0");
	addCoupling(this, "executor1in", hub, "status1");
	addCoupling(this, "executor2in", hub, "status2");
	addCoupling(hub, "out0", this, "executor0out");
	addCoupling(hub, "out1", this, "executor1out");
	addCoupling(hub, "out2", this, "executor2out");

	addTestInput("trigger", new entity("GitHub Pull Request"), 0);
	addTestInput("trigger", new entity("Beta System Deployment"), 0);
	addTestInput("trigger", new entity("Scheduled Suite Execution"), 0);
    }
    
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(591, 269);
	
    }
}
