/*     
 *    
 *  Author     : Neal DeBuhr
 *  Version    : DEVS-Suite 3.0.0  
 *  Date       : 12-27-2017
 */
package CoreOne;
import java.awt.*;

import GenCol.*;

import model.modeling.*;
import model.simulation.*;

import view.modeling.ViewableAtomic;
import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;
import view.simView.*;

public class TestingEngine extends ViewableDigraph {
    protected int numberNodes;
    protected int numberJobs;
    private ViewableDigraph jenkins;
    private ViewableAtomic github;
    private ViewableAtomic node0;
    private ViewableAtomic node1;
    private ViewableAtomic node2;
    private ViewableAtomic site;
    
    public TestingEngine(){
	super("TestingEngine");
	numberNodes = 3; //For later extensibility
	numberJobs = 10; //For later extensibility
	
	jenkins = new Jenkins();
	github = new GithubRepo();
	node0 = new SeleniumGridNode("SeleniumGridNode0", 1);
	node1 = new SeleniumGridNode("SeleniumGridNode1", 1);
	node2 = new SeleniumGridNode("SeleniumGridNode2", 1);
	site = new SimpleDjangoSite();
	
	add(jenkins);
	add(github);
	add(node0);
	add(node1);
	add(node2);
	add(site);

	addCouplings();
    }
    
    private void addCouplings(){
	addCoupling(github, "out", jenkins, "github-in");
	addCoupling(jenkins, "github-out", github, "in");

	addCoupling(node0, "out", jenkins, "executor0-in");
	addCoupling(node1, "out", jenkins, "executor1-in");
	addCoupling(node2, "out", jenkins, "executor2-in");
	addCoupling(jenkins, "executor0-out", node0, "in");
	addCoupling(jenkins, "executor1-out", node1, "in");
	addCoupling(jenkins, "executor2-out", node2, "in");

	addCoupling(jenkins, "results", site, "in");
    }
    
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(591, 269);
	
    }
}
