#!/usr/bin/env bash

# hydrotest
# HydroTest Control Script
# Author: Neal DeBuhr
# Modified by: Devin Cowan

display_usage() {
    echo "*** HydroTest Control Script ***"
    echo "usage: $0 hydroclient [args]  # runs tests within the hydroclient test suite"
    echo "usage: $0 hydroshare [args]   # runs tests within the hydroshare test suite"
    echo "usage: $0 check               # checks files against repository Flake8 standards"
}

run_hydroshare() {
    echo "HYDROSHARE:"
    echo "PYTHONPATH=. python3 hydroshare/hydroshare.py ${@:2}"
    PYTHONPATH=. python3 hydroshare/hydroshare.py ${@:2}
}

run_hydroclient() {
    echo "HYDROCLIENT:"
    echo "PYTHONPATH=. python3 hydroclient/hydroclient.py ${@:2}"
    PYTHONPATH=. python3 hydroclient/hydroclient.py ${@:2}
}

run_check() {
    echo "CUAHSI_BASE:"
    echo "flake8 --config=cuahsi_base/setup.cfg ."
    flake8 --config=cuahsi_base/setup.cfg .
}

### Display usage if no arguments provided ###
if [  $# -eq 0 ]
then
    display_usage
    exit 1
fi

case "$1" in
    hydroshare) run_hydroshare "$@"
        ;;
    hydroclient) run_hydroclient "$@"
        ;;
    check) run_check "$@"
        ;;
    *) display_usage
        ;;
esac

exit 0;
