WORKSPACE_CREATE_ARCHIVE_DELAY = 60
SEARCH_IN_PROGRESS_DELAY = 5
SEARCH_AUTOCOMPLETE_DELAY = 5
WORKSPACE_TOOLTIP_DISAPPEAR = 5
MODAL_FADE_DELAY = 5
NEW_PAGE_LOAD_DELAY = 5
FILTER_MODAL_OPEN_DELAY = 5
HSAPI_GUI_RESPONSE_DELAY = 30
