---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: repeater
  name: repeater
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: repeater
  template:
    metadata:
      labels:
        app: repeater
    spec:
      containers:
      - name: repeater
        image: ubuntu:20.04
        command: ["/bin/bash", "-c"]
        args: ["sleep 86400"]
        ports:
        - name: http
          containerPort: 443
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
        volumeMounts:
        - name: repeater-opt
          mountPath: /opt
      volumes:
      - name: repeater-opt
        persistentVolumeClaim:
          claimName: repeater-opt
      restartPolicy: Always
status: {}
---
kind: Service
apiVersion: v1
metadata:
  name: repeater
spec:
  type: LoadBalancer
  selector:
    app: repeater
  ports:
  - name: http
    port: 443
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: repeater-opt
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi