selenium-hub:
  image: selenium/hub
  ports:
  - 4444:4444
  expose:
  - "5555"

chrome:
  image: ${REPOSITORY}/node-debug-chrome:latest
  links:
  - selenium-hub:hub
  volumes:
  - /dev/shm:/dev/shm # Mitigates the Chromium issue described at https://code.google.com/p/chromium/issues/detail?id=519952
  ports:
  - "5901-5950:5900"

firefox:
  image: ${REPOSITORY}/node-debug-firefox:latest
  environment:
    HUB_PORT_4444_TCP_ADDR: hub
  links:
  - selenium-hub:hub
  ports:
  - "5951-5999:5900"
