version: '2'
services:
  selenium-hub:
    image: selenium/hub
    ports:
    - 4444:4444
    networks:
    - cuahsi_ci
  chrome:
    image: ${REPOSITORY}/node-debug-chrome:latest
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
    links:
    - selenium-hub:hub
    volumes:
    - /dev/shm:/dev/shm # Mitigates the Chromium issue described at https://code.google.com/p/chromium/issues/detail?id=519952
    ports:
    - "5901-5950:5900"
    depends_on:
    - selenium-hub
    networks:
    - cuahsi_ci
  firefox:
    image: ${REPOSITORY}/node-debug-firefox:latest
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
    links:
    - selenium-hub:hub
    depends_on:
    - selenium-hub
    ports:
    - "5951-5999:5900"
    networks:
    - cuahsi_ci
networks:
  cuahsi_ci:
    external:
      name: cuahsi_ci