version: '2'
services:
  jenkins:
    build:
        context: .
        dockerfile: DockerfileJenkins
    ports:
     - "8080:8080"
     - "50000:50000"
    volumes:
     - .:/var/jenkins_home/cuahsi/
    networks:
     - cuahsi_ci
networks:
  cuahsi_ci:
    external:
      name: cuahsi_ci
