name: Run DSP Tests

on:
  push:
    branches: [auth-timings]
  pull_request:
    branches: [master]
    paths:
      - "dsp/**"
      - ".github/workflows/**"
  workflow_dispatch:
    inputs:
      dsp-front-ref:
        description: 'Ref from DSP front'
      dsp-back-ref:
        description: 'Ref from DSP back'
      target:
        description: 'Alternative to Refs above, URL to target tests (ex: https://dsp-beta.criticalzone.org/). If all inputs blank, will run against dsp-test'
      use-gh-env:
        type: boolean
        description: Use dspback .env file stored in GH secrets (vs default in dspback repo)

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip3 install -r requirements.txt

      - name: Prepare Selenium
        run: sudo apt-get install -y chromium-browser

      # - name: Prepare Firefox
      # TODO: enable browser selection via GH dispatch
      #   # uses: browser-actions/setup-firefox@latest
      #   run: sudo apt install firefox

      # - name: Firefox version
      #   run: firefox --version

      # - name: Geckodriver
      #   run: sudo apt install firefox-geckodriver

      - name: Create Output Dir
        run: mkdir output
      
      - name: Retrieve base64 from secrets and decode to .env file
        env:
          DSP_QA_ENGINE_ENV_BASE64: ${{ secrets.DSP_QA_ENGINE_ENV_BASE64 }}
        run: |
          echo $DSP_QA_ENGINE_ENV_BASE64 | base64 --decode > .env
      
      - name: Run Tests against dsp-test
        if: (github.event.inputs.dsp-front-ref == '' ||  github.event.inputs.dsp-back-ref == '') && github.event.inputs.target == ''
        run: |
          ./hydrotest dsp DspHydroshareTestSuite.test_hs_000002_auth_then_nav_to_submit --headless --browser chrome --base https://dsp-alpha.criticalzone.org/ 2>&1 | tee -a output/hydroshare-browser-test.txt
        # ./hydrotest dsp DspExternalTestSuite --headless --browser chrome --base https://dsp-test.criticalzone.org/ 2>&1 | tee -a output/external-browser-test.txt
        # ./hydrotest dsp DspZenodoTestSuite --headless --browser chrome --base https://dsp-test.criticalzone.org/ 2>&1 | tee -a output/zenodo-browser-test.txt
        # ./hydrotest dsp DspEarthchemTestSuite --headless --browser chrome --base https://dsp-test.criticalzone.org/ 2>&1 | tee -a output/earthchem-browser-test.txt
      
      - name: Archive test results
        uses: actions/upload-artifact@v3
        with:
          name: DSP-ARTIFACTS
          path: output
      
      - name: Archive debug
        uses: actions/upload-artifact@v3
        with:
          name: DSP-DEBUG
          path: debug

      - name: Check whether passing
        working-directory: output
        run: |
          if grep -rl -e "FAILED (" -e "ERROR:" . >/dev/null; then grep -rh -e "FAIL:" -e "ERROR:" . && exit 1; else grep -rh "OK (" .; fi
