name: Run DSP Tests

on:
  pull_request:
    branches: [master]
    paths:
      - "dsp/**"
      - ".github/workflows/**"
  workflow_dispatch:
    inputs:
      dsp-front-ref:
        description: 'Ref from DSP front'
      dsp-back-ref:
        description: 'Ref from DSP back'
      use-gh-env:
        type: boolean
        description: Use dspback .env file stored in GH secrets (vs default in dspback repo)

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip3 install -r requirements.txt

      # https://github.com/SeleniumHQ/selenium/blob/selenium-4.0.0-beta-3/.github/actions/setup-chrome/action.yml
      - name: Prepare Selenium
        run: |
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee -a /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update -qqy
          sudo apt-get -qqy install google-chrome-stable
          CHROME_VERSION=$(google-chrome-stable --version)
          CHROME_FULL_VERSION=${CHROME_VERSION%%.*}
          CHROME_MAJOR_VERSION=${CHROME_FULL_VERSION//[!0-9]}
          sudo rm /etc/apt/sources.list.d/google-chrome.list
          export CHROMEDRIVER_VERSION=`curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_MAJOR_VERSION%%.*}`
          curl -L -O "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip && chmod +x chromedriver && sudo mv chromedriver /usr/local/bin
          export CHROMEDRIVER_VERSION=`curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_MAJOR_VERSION%%.*}`
          curl -L -O "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip && chmod +x chromedriver && sudo mv chromedriver /usr/local/bin
          chromedriver -version
        shell: bash

      # - name: Prepare Selenium
      #   uses: nanasess/setup-chromedriver@v1
      # https://github.com/marketplace/actions/setup-chromedriver
      # with:
      #   # Optional: do not specify to match Chrome's version
      #   chromedriver-version: '88.0.4324.96'
      # - run: |
      #     export DISPLAY=:99
      #     chromedriver --url-base=/wd/hub &
      #     # sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional

      # - name: Prepare Firefox
      #   # uses: browser-actions/setup-firefox@latest
      #   run: sudo apt install firefox

      # - name: Firefox version
      #   run: firefox --version

      # - name: Geckodriver
      #   run: sudo apt install firefox-geckodriver

      - name: Create Output Dir
        run: mkdir output
      
      - name: Retrieve base64 from secrets and decode to .env file
        env:
          DSP_QA_ENGINE_ENV_BASE64: ${{ secrets.DSP_QA_ENGINE_ENV_BASE64 }}
        run: |
          echo $DSP_QA_ENGINE_ENV_BASE64 | base64 --decode > .env

      - name: Run Tests against dsp-test
        if: github.event.inputs.dsp-front-ref == '' ||  github.event.inputs.dsp-back-ref == ''
        run: |
          ./hydrotest dsp DspHydroshareTestSuite --headless --browser chrome --base https://dsp-test.criticalzone.org/ 2>&1 | tee -a output/hydroshare-browser-test.txt
          ./hydrotest dsp DspExternalTestSuite --headless --browser chrome --base https://dsp-test.criticalzone.org/ 2>&1 | tee -a output/external-browser-test.txt
          ./hydrotest dsp DspZenodoTestSuite --headless --browser chrome --base https://dsp-test.criticalzone.org/ 2>&1 | tee -a output/zenodo-browser-test.txt
          ./hydrotest dsp DspEarthchemTestSuite --headless --browser chrome --base https://dsp-test.criticalzone.org/ 2>&1 | tee -a output/earthchem-browser-test.txt
      
      - name: Clone DSP Back, ref = ${{ github.event.inputs.dsp-back-ref }}
        uses: actions/checkout@v2
        if: github.event.inputs.dsp-front-ref != '' &&  github.event.inputs.dsp-back-ref != ''
        with:
          repository: cznethub/dspback
          path: dspback
          ref: ${{ github.event.inputs.dsp-back-ref }}
      
      - name: Retrieve base64 from secrets and decode to .env file
        working-directory: dspback
        if: github.event.inputs.dsp-front-ref != '' &&  github.event.inputs.dsp-back-ref != '' && github.event.inputs.use-gh-env == 'true'
        env:
          DSP_TEST_ENV_BASE64: ${{ secrets.DSP_TEST_ENV_BASE64 }}
        run: |
          echo $DSP_TEST_ENV_BASE64 | base64 --decode > .env
      
      - name: Build DSPBack
        working-directory: dspback
        if: github.event.inputs.dsp-front-ref != '' &&  github.event.inputs.dsp-back-ref != ''
        run: make build
      
      - name: Clone DSP Front, ref = ${{ github.event.inputs.dsp-front-ref }}
        uses: actions/checkout@v2
        if: github.event.inputs.dsp-front-ref != '' &&  github.event.inputs.dsp-back-ref != ''
        with:
          repository: cznethub/dspfront
          path: dspfront
          ref: ${{ github.event.inputs.dsp-front-ref }}
      
      - name: Build DSPFront
        working-directory: dspfront
        if: github.event.inputs.dsp-front-ref != '' &&  github.event.inputs.dsp-back-ref != ''
        run: docker build -t dspfront .
      
      - name: Startup containers
        if: github.event.inputs.dsp-front-ref != '' &&  github.event.inputs.dsp-back-ref != ''
        working-directory: dspback
        run: make up-all-d

      - name: Sleep for 10 seconds
        if: github.event.inputs.dsp-front-ref != '' &&  github.event.inputs.dsp-back-ref != ''
        run: sleep 10s
        shell: bash
      
      - name: Check 200 from DSP
        # Fail fast if dsp isn't up
        if: github.event.inputs.dsp-front-ref != '' &&  github.event.inputs.dsp-back-ref != ''
        run: |
          ./hydrotest dsp DspTestSuite.test_base_000001_home_page --headless --browser chrome --base https://localhost 2>&1 | tee -a output/home_page_check.txt
          if grep -rl "FAILED (" ./output >/dev/null; then echo "Failed to connect" && exit 1; fi

      - name: Run Tests against localhost
        if: github.event.inputs.dsp-front-ref != '' &&  github.event.inputs.dsp-back-ref != ''
        run: |
          ./hydrotest dsp DspHydroshareTestSuite --headless --browser chrome --base https://localhost 2>&1 | tee -a output/hydroshare-browser-test.txt
          ./hydrotest dsp DspExternalTestSuite --headless --browser chrome --base https://localhost 2>&1 | tee -a output/external-browser-test.txt
          ./hydrotest dsp DspZenodoTestSuite --headless --browser chrome --base https://localhost 2>&1 | tee -a output/zenodo-browser-test.txt
          ./hydrotest dsp DspEarthchemTestSuite --headless --browser chrome --base https://localhost 2>&1 | tee -a output/earthchem-browser-test.txt

      - name: Archive test results
        uses: actions/upload-artifact@v3
        with:
          name: DSP-ARTIFACTS
          path: output

      - name: Check whether passing
        working-directory: output
        run: |
          grep -rh "ERROR:" .
          if grep -rl "FAILED (" . >/dev/null; then grep -rh "FAIL:" . && exit 1; else grep -rh "OK (" .; fi
